<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <Authors>ycanardeau</Authors>
    <Description>Saruhashi is a UI framework for MonoGame.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ycanardeau/Saruhashi</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ycanardeau/Saruhashi</RepositoryUrl>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Extended" Version="6.1.1" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aigamo.Saruhashi\Aigamo.Saruhashi.csproj" />
  </ItemGroup>

</Project>
